### ISSUE TITLE
JavaFormat format task should work with AOT projects

### ISSUE THREAD

**Issue by jzheaux** [spring-io/spring-javaformat#424] opened 2024-09-25 20:21 UTC
If I [create a project](https://github.com/jzheaux/javaformat-aot) that uses `io.spring.javaformat` and also the needed Boot and other plugins to support AOT compilation, then `./gradlew check` and `./gradlew format` fail. This ticket focuses on making `./gradlew format` work.

The error is the following:

```
A problem was found with the configuration of task ':formatMain' (type 'Format').
  - Gradle detected a problem with the following location: '/home/jzheaux/tmp/javaformat-aot/src/main/java'.
    
    Reason: Task ':compileJava' uses this output of task ':formatMain' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.
    
    Possible solutions:
      1. Declare task ':formatMain' as an input of ':compileJava'.
      2. Declare an explicit dependency on ':formatMain' from ':compileJava' using Task#dependsOn.
      3. Declare an explicit dependency on ':formatMain' from ':compileJava' using Task#mustRunAfter.
```

You can see this by running `./gradlew format` on the linked [sample](https://github.com/jzheaux/javaformat-aot).

I can fix it by following the instructions from the Gradle error:

```
compileJava {
    dependsOn("formatMain")
}
compileTestJava {
    dependsOn("formatTest")
}
```

This isn't ideal, though, since I'd prefer to be able to run `format` and `check` independently from one another.

For additional context, this comes up in [the Spring Security Samples project](https://github.com/spring-projects/spring-security-samples), where we use JavaFormat to keep the samples uniform. When we recently added [an AOT sample](https://github.com/spring-projects/spring-security-samples/tree/main/servlet/spring-boot/java/aot/data), we ran into this behavior.

**Comment by wilkinsona** [comment] 2024-09-26 10:03
I think this is really a duplicate of #425. Just as, ideally, Java Format wouldn't check AOT generated source, I also think that it shouldn't bother formatting it either. It feels like we need a mechanism by which Java Format can ignore the `aot` source set entirely.

**Closed by wilkinsona** 2024-09-26 10:03 UTC
