### ISSUE TITLE
OOM on save/refactor

### ISSUE THREAD

**Issue by dsyer** [spring-io/spring-javaformat#139] opened 2019-09-06 10:06 UTC
Not sure how to trigger this. I'm getting UI hangs and eventual OOM on save/refactor changes. Uninstalling this feature "fixes" the issue.

Example stack trace:

```
java.lang.reflect.InvocationTargetException
    at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:449)
    at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:354)
    at org.eclipse.ui.internal.WorkbenchWindow.lambda$5(WorkbenchWindow.java:2364)
    at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)
    at org.eclipse.ui.internal.WorkbenchWindow.run(WorkbenchWindow.java:2362)
    at org.eclipse.jdt.internal.ui.refactoring.RefactoringExecutionHelper.perform(RefactoringExecutionHelper.java:199)
    at org.eclipse.jdt.internal.ui.refactoring.RefactoringExecutionHelper.perform(RefactoringExecutionHelper.java:156)
    at org.eclipse.jdt.ui.refactoring.RenameSupport.perform(RenameSupport.java:201)
    at org.eclipse.jdt.internal.ui.refactoring.reorg.RenameLinkedMode.doRename(RenameLinkedMode.java:371)
    at org.eclipse.jdt.internal.ui.refactoring.reorg.RenameLinkedMode$EditorSynchronizer.left(RenameLinkedMode.java:125)
    at org.eclipse.jface.text.link.LinkedModeModel.exit(LinkedModeModel.java:338)
    at org.eclipse.jface.text.link.LinkedModeUI.lambda$2(LinkedModeUI.java:1174)
    at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
    at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
    at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5113)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4666)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
    at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
    at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
    at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:635)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1441)
Caused by: java.lang.OutOfMemoryError: Java heap space
```

**Comment by wilkinsona** [comment] 2019-09-06 10:10
Could you run with `-XX:+HeapDumpOnOutOfMemoryError` and share the resulting dump so that we can see what's consuming all the heap?

**Comment by dsyer** [comment] 2019-09-06 12:45
Any idea where the file is created?

**Comment by dsyer** [comment] 2019-09-06 12:46
Maybe it's just this (from the Eclispe error view):

```
java.lang.reflect.InvocationTargetException
	at org.eclipse.jface.operation.ModalContext.runInCurrentThread(ModalContext.java:449)
	at org.eclipse.jface.operation.ModalContext.run(ModalContext.java:354)
	at org.eclipse.ui.internal.WorkbenchWindow.lambda$5(WorkbenchWindow.java:2364)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)
	at org.eclipse.ui.internal.WorkbenchWindow.run(WorkbenchWindow.java:2362)
	at org.eclipse.jdt.internal.ui.refactoring.RefactoringExecutionHelper.perform(RefactoringExecutionHelper.java:199)
	at org.eclipse.jdt.internal.ui.refactoring.RefactoringExecutionHelper.perform(RefactoringExecutionHelper.java:156)
	at org.eclipse.jdt.ui.refactoring.RenameSupport.perform(RenameSupport.java:201)
	at org.eclipse.jdt.internal.ui.refactoring.reorg.RenameLinkedMode.doRename(RenameLinkedMode.java:371)
	at org.eclipse.jdt.internal.ui.refactoring.reorg.RenameLinkedMode$EditorSynchronizer.left(RenameLinkedMode.java:125)
	at org.eclipse.jface.text.link.LinkedModeModel.exit(LinkedModeModel.java:338)
	at org.eclipse.jface.text.link.LinkedModeUI.lambda$2(LinkedModeUI.java:1174)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5113)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4666)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1173)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1062)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:635)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:559)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:150)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:155)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1441)
Caused by: java.lang.OutOfMemoryError: Java heap space
Root exception:
java.lang.OutOfMemoryError: Java heap space
```

**Comment by wilkinsona** [comment] 2019-09-06 13:10
Yeah, it should be a file written to the JVM's working directory. You can control the location use `-XX:HeapDumpPath`.

**Comment by dsyer** [comment] 2019-09-06 13:29
With `-XX:HeapDumpPath=/tmp` I see these files:

```
$ find /tmp/hsperfdata_dsyer/
/tmp/hsperfdata_dsyer/
/tmp/hsperfdata_dsyer/21356
/tmp/hsperfdata_dsyer/21441
```

and 21356 is the PID of my Eclipse process. But none of them looks like a heap dump.

**Comment by wilkinsona** [comment] 2019-09-06 13:37
As far as I know `hsperfdata_<username>/<pid>` is unrelated to dumping the heap on OOME and is created by default.

**Comment by dsyer** [comment] 2019-09-06 14:48
Maybe Eclipse is catching the OOM error and the JVM never sees it?

**Comment by wilkinsona** [comment] 2019-09-06 16:33
Sounds plausible (and annoying). Can you get anything with `jmap` or the like immediately after Eclipse barfs?

**Comment by martinlippert** [comment] 2019-09-09 12:52
I tried to analyze this a bit more. It seems to be easy to reproduce:

- use latest STS4 on Eclipse 2019-09 (maybe this also works with latest Eclipse 2019-09 milestone builds)
- install latest java-formatter version (I got 0.0.15)
- go to `Preferences -> Java -> Code Style -> Formatter`
- switch the implementation to `Spring`
- the IDE immediately runs out of heap

Looking under the hood, I can see this allocating more than 250MB:

`DefaultCodeFormatter.java:207 io.spring.javaformat.formatter.eclipse.DefaultCodeFormatter.tokenizeSource(int)`

This is already when formatting the preview for the preferences dialog (so nothing seriously large). Maybe something changed in the internals of Eclipse that causes the java formatter to blow up.

Is there an easy way to setup a dev environment for this that would allow be to debug this? I can't even find this type in the GitHub repo, but maybe I am looking at the wrong place?

**Comment by wilkinsona** [comment] 2019-09-09 13:24
Thanks for taking a look, @martinlippert.

`DefaultCodeFormatter` is repackaged from `org.eclipse.jdt.internal.formatter.DefaultCodeFormatter`. It builds against Eclipse 2019-03 at the moment. Perhaps there's a bug/change in Eclipse 2019-09 that's adversely affected the behaviour of `tokenizeSource(int)`?

The contributing guidelines contain some instruction on how to set up [a dev environment using Eclipse](https://github.com/spring-io/spring-javaformat/blob/b6611a1adc957a4633b04eb8f8b330b460490164/CONTRIBUTING.adoc#importing-into-eclipse).

**Comment by martinlippert** [comment] 2019-09-09 13:45
There is indeed a change in the DefaultCodeFormatter in the way it creates the scanner: https://github.com/eclipse/eclipse.jdt.core/commit/5d58390bf2fb018a53c69e075d1416a113301107#diff-e4b25e2704c57f755dad0d2673d243c0

Haven't looked into the details yet though...

**Comment by BoykoAlex** [comment] 2019-09-24 20:05
Upgrading to Eclipse 2019-09 (4.13) makes it work for STS based on that Eclipse version (and higher). However, Eclipse 2019-06 (4.12) doesn't work with the Spring formatter...
Is that a problem?
If yes, any chance different versions fo Spring Java Formatter can be provided for different Eclipse versions?

**Comment by magJ** [comment] 2019-10-18 02:50
Not sure if this is the same issue, but I am also getting a memory leak when running the gradle plugin.

Looking at the dominator tree of the heap dump via eclipse MAT shows:
```plain
Class Name                                                                         | Shallow Heap | Retained Heap | Percentage
-------------------------------------------------------------------------------------------------------------------------------
io.spring.javaformat.formatter.Formatter$DelegateCodeFormatter @ 0x7f71c7700       |           56 |   165,206,040 |     80.74%
|- java.util.ArrayList @ 0x7f62ea570                                               |           24 |   165,204,128 |     80.74%
|  '- java.lang.Object[2734845] @ 0x7ff200000                                      |   10,939,400 |   165,204,104 |     80.74%
|     |- io.spring.javaformat.formatter.eclipse.Token @ 0x7f62c5dc8                |           64 |            64 |      0.00%
|     |- io.spring.javaformat.formatter.eclipse.Token @ 0x7f62c5e08                |           64 |            64 |      0.00%
|     |- io.spring.javaformat.formatter.eclipse.Token @ 0x7f62c5e48                |           64 |            64 |      0.00%
|     |- io.spring.javaformat.formatter.eclipse.Token @ 0x7f62c5e88                |           64 |            64 |      0.00%
|     |- io.spring.javaformat.formatter.eclipse.Token @ 0x7f62c5ec8                |           64 |            64 |      0.00%
|     |- io.spring.javaformat.formatter.eclipse.Token @ 0x7f62c5f08                |           64 |            64 |      0.00%
|     |- io.spring.javaformat.formatter.eclipse.Token @ 0x7f62c5f48                |           64 |            64 |      0.00%
|     |- io.spring.javaformat.formatter.eclipse.Token @ 0x7f62c5f88                |           64 |            64 |      0.00%
|     |- io.spring.javaformat.formatter.eclipse.Token @ 0x7f62c5fc8                |           64 |            64 |      0.00%
|     |- io.spring.javaformat.formatter.eclipse.Token @ 0x7f62c6008                |           64 |            64 |      0.00%
|     |- io.spring.javaformat.formatter.eclipse.Token @ 0x7f62c6048                |           64 |            64 |      0.00%
|     |- io.spring.javaformat.formatter.eclipse.Token @ 0x7f62c6088                |           64 |            64 |      0.00%
|     |- io.spring.javaformat.formatter.eclipse.Token @ 0x7f62c60c8                |           64 |            64 |      0.00%
|     |- io.spring.javaformat.formatter.eclipse.Token @ 0x7f62c6108                |           64 |            64 |      0.00%
|     |- io.spring.javaformat.formatter.eclipse.Token @ 0x7f62c6148                |           64 |            64 |      0.00%
|     |- io.spring.javaformat.formatter.eclipse.Token @ 0x7f62c6188                |           64 |            64 |      0.00%
|     |- io.spring.javaformat.formatter.eclipse.Token @ 0x7f62c61c8                |           64 |            64 |      0.00%
|     |- io.spring.javaformat.formatter.eclipse.Token @ 0x7f62c6208                |           64 |            64 |      0.00%
|     |- io.spring.javaformat.formatter.eclipse.Token @ 0x7f62c6248                |           64 |            64 |      0.00%
|     |- io.spring.javaformat.formatter.eclipse.Token @ 0x7f62c6288                |           64 |            64 |      0.00%
|     |- io.spring.javaformat.formatter.eclipse.Token @ 0x7f62c62c8                |           64 |            64 |      0.00%
|     |- io.spring.javaformat.formatter.eclipse.Token @ 0x7f62c6308                |           64 |            64 |      0.00%
|     |- io.spring.javaformat.formatter.eclipse.Token @ 0x7f62c6348                |           64 |            64 |      0.00%
|     |- io.spring.javaformat.formatter.eclipse.Token @ 0x7f62c6388                |           64 |            64 |      0.00%
|     |- io.spring.javaformat.formatter.eclipse.Token @ 0x7f62c63c8                |           64 |            64 |      0.00%
|     '- Total: 25 of 2,410,386 entries; 2,410,361 more                            |              |               |           
|- io.spring.javaformat.formatter.eclipse.DefaultCodeFormatterOptions @ 0x7f62ea5e0|          640 |           736 |      0.00%
|- io.spring.javaformat.formatter.eclipse.DefaultCodeFormatterOptions @ 0x7f62eaa60|          640 |           736 |      0.00%
|- io.spring.javaformat.formatter.eclipse.TokenManager @ 0x7f62ea538               |           56 |           248 |      0.00%
|- java.util.ArrayList @ 0x7f62ea3c8                                               |           24 |           112 |      0.00%
|- java.util.Arrays$ArrayList @ 0x7f7374c90                                        |           24 |            24 |      0.00%
'- Total: 6 entries                                                                |              |               |           
-------------------------------------------------------------------------------------------------------------------------------
```

**Comment by wilkinsona** [comment] 2019-10-18 09:41
@magJ Interesting, thank you. I suspect that this is a different issue as we believe that the problem reported here is due to an incompatibility between this project's Eclipse plugin (that is built against Eclipse 2019-03) and Eclipse 2019-09.

Could you please open a new issue for the memory leak with the Gradle plugin so that it doesn't get forgotten? It'd be much appreciated if you could attach a small sample project with some steps to reproduce it.

**Comment by magJ** [comment] 2019-10-18 12:44
@wilkinsona I have opened #148 and provided a demo project.

**Comment by philwebb** [comment] 2019-12-03 18:22
Closing in favor of PR #143

**Closed by philwebb** 2019-12-03 18:22 UTC
