### ISSUE TITLE
lambda

### ISSUE THREAD

**Issue by tonycody** [spring-io/spring-javaformat#282] opened 2021-09-09 10:03 UTC
Can lambda be optimized to render better?

**Comment by wilkinsona** [comment] 2021-09-09 10:12
What do you think could be improved? Can you provide some examples of the current output and equivalent examples where you think the formatting's better?

**Comment by tonycody** [comment] 2021-09-09 10:52
> What do you think could be improved? Can you provide some examples of the current output and equivalent examples where you think the formatting's better?
You can refer to it
https://github.com/palantir/palantir-java-format
![image](https://user-images.githubusercontent.com/6773121/132673172-24c5fd50-25a5-4eae-a4a2-d4c8955c769a.png)

**Comment by wilkinsona** [comment] 2021-09-09 11:47
Thanks. The before in the image above doesn't match the behaviour of this formatter. This formatter formats that code as follows:

```java
private static void configureResolvedVersionsWithVersionMapping(Project project) {
    project.getPluginManager().withPlugin("maven-publish", plugin -> {
        project.getExtensions().getByType(PublishingExtension.class).getPublications()
                .withType(MavenPublication.class)
                .configureEach(publication -> publication.versionMapping(mapping -> {
                    mapping.allVariants(VariantVersionMappingStrategy::fromResolutionResult);
                }));
    });
}
```

Further changes, such as placing `getByType(PublishingExtension.class)` and `getPublications()` on separate lines is a duplicate of https://github.com/spring-io/spring-javaformat/issues/124.

**Closed by wilkinsona** 2021-09-09 11:47 UTC
