### ISSUE TITLE
Allow java format to not wrap stream calls

### ISSUE THREAD

**Issue by cbelizone2y** [spring-io/spring-javaformat#261] opened 2021-02-11 14:52 UTC
I really love the plugin, but I think it's need a little bit of configuration to avoid wrapping every chained call, for streams is a nightmare, it's not the same reading this code block:

```java
Stream.ofNullable(shops.getShops())
            .flatMap(Collection::stream)
	    .map(converter::convert)
	    .collect(Collectors.toList());
```

Than this one, after the java format has been executed:
```java
Stream.ofNullable(shops.getShops()).flatMap(Collection::stream)
	    .map(converter::convert).collect(Collectors.toList());
```

**Comment by wilkinsona** [comment] 2021-02-11 15:29
Thanks for the suggestion. This is a duplicate of https://github.com/spring-io/spring-javaformat/issues/124.

**Closed by wilkinsona** 2021-02-11 15:29 UTC
