### ISSUE TITLE
format exception

### ISSUE THREAD

**Issue by duanhairuo** [spring-io/spring-javaformat#99] opened 2019-04-11 03:17 UTC
```
Caused by: io.spring.javaformat.formatter.FileFormatterException: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
    at io.spring.javaformat.formatter.FileFormatterException.wrap (FileFormatterException.java:47)
    at io.spring.javaformat.formatter.FileFormatter.formatFile (FileFormatter.java:87)
    at io.spring.javaformat.formatter.FileFormatter.lambda$formatFiles$1 (FileFormatter.java:71)
    at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:193)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining (ArrayList.java:1382)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:471)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential (ForEachOps.java:151)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential (ForEachOps.java:174)
    at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach (ReferencePipeline.java:418)
    at io.spring.format.maven.ApplyMojo.execute (ApplyMojo.java:46)
    at io.spring.format.maven.FormatMojo.execute (FormatMojo.java:101)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
    at java.util.ArrayList.rangeCheck (ArrayList.java:657)
    at java.util.ArrayList.get (ArrayList.java:433)
    at io.spring.javaformat.formatter.eclipse.CommentsPreparator.alignJavadocTag (CommentsPreparator.java:692)
    at io.spring.javaformat.formatter.eclipse.CommentsPreparator.handleJavadocTagAlignment (CommentsPreparator.java:686)
    at io.spring.javaformat.formatter.eclipse.CommentsPreparator.visit (CommentsPreparator.java:556)
    at org.eclipse.jdt.core.dom.Javadoc.accept0 (Javadoc.java:191)
    at org.eclipse.jdt.core.dom.ASTNode.accept (ASTNode.java:2815)
    at io.spring.javaformat.formatter.eclipse.DefaultCodeFormatter.prepareComments (DefaultCodeFormatter.java:424)
    at io.spring.javaformat.formatter.eclipse.DefaultCodeFormatter.prepareFormattedCode (DefaultCodeFormatter.java:229)
    at io.spring.javaformat.formatter.eclipse.DefaultCodeFormatter.format (DefaultCodeFormatter.java:184)
    at io.spring.javaformat.formatter.eclipse.DefaultCodeFormatter.format (DefaultCodeFormatter.java:166)
    at io.spring.javaformat.formatter.Formatter.lambda$format$0 (Formatter.java:104)
    at io.spring.javaformat.formatter.Formatter.nlsSafe (Formatter.java:155)
    at io.spring.javaformat.formatter.Formatter.format (Formatter.java:103)
    at io.spring.javaformat.formatter.Formatter.format (Formatter.java:96)
    at io.spring.javaformat.formatter.Formatter.format (Formatter.java:85)
    at io.spring.javaformat.formatter.FileFormatter.formatFile (FileFormatter.java:83)
    at io.spring.javaformat.formatter.FileFormatter.lambda$formatFiles$1 (FileFormatter.java:71)
    at java.util.stream.ReferencePipeline$3$1.accept (ReferencePipeline.java:193)
    at java.util.ArrayList$ArrayListSpliterator.forEachRemaining (ArrayList.java:1382)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:481)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:471)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential (ForEachOps.java:151)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential (ForEachOps.java:174)
    at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach (ReferencePipeline.java:418)
    at io.spring.format.maven.ApplyMojo.execute (ApplyMojo.java:46)
    at io.spring.format.maven.FormatMojo.execute (FormatMojo.java:101)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
[ERROR]
```

**Comment by philwebb** [comment] 2019-04-11 17:59
Do you have a consistent way to reproduce the error? Can you attach a snippet of code that causes it?

**Comment by wilkinsona** [comment] 2019-06-25 09:42
Closing due to the lack of the requested feedback. We can re-open if a snippet of code that causes the failure is provided.

**Closed by wilkinsona** 2019-06-25 09:42 UTC
