### ISSUE TITLE
Eclipse JDT 3.22.0 causes IndexOutOfBoundsException

### ISSUE THREAD

**Issue by funfried** [spring-io/spring-javaformat#204] opened 2020-06-29 20:10 UTC
Hi,
I'm writing a NetBeans Plugin which adds external code formatters to the IDE (you can find it in externalcodeformatter_for_netbeans in my GitHub repositories). It supports the Eclipse Java Code Formatter (JDT) and the Spring Java Code Formatter amongst others. Since I changed my Eclipse dependencies to the newest versions (3.22.0) of Eclipse JDT, I get this exception when I try to format with the Spring code formatter

```
java.lang.IndexOutOfBoundsException: Index 13 out of bounds for length 13
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:373)
	at java.base/java.util.ArrayList.get(ArrayList.java:425)
	at io.spring.javaformat.formatter.eclipse.TokenManager.get(TokenManager.java:75)
	at io.spring.javaformat.formatter.eclipse.TokenManager.findIndex(TokenManager.java:168)
	at io.spring.javaformat.formatter.eclipse.SpacePreparator.handleToken(SpacePreparator.java:1098)
	at io.spring.javaformat.formatter.eclipse.SpacePreparator.visit(SpacePreparator.java:197)
	at org.eclipse.jdt.core.dom.EnumDeclaration.accept0(EnumDeclaration.java:253)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2971)
	at org.eclipse.jdt.core.dom.ASTNode.acceptChildren(ASTNode.java:3042)
	at org.eclipse.jdt.core.dom.CompilationUnit.accept0(CompilationUnit.java:258)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2971)
	at io.spring.javaformat.formatter.eclipse.DefaultCodeFormatter.prepareSpaces(DefaultCodeFormatter.java:412)
	at io.spring.javaformat.formatter.eclipse.DefaultCodeFormatter.prepareFormattedCode(DefaultCodeFormatter.java:229)
	at io.spring.javaformat.formatter.eclipse.DefaultCodeFormatter.format(DefaultCodeFormatter.java:186)
	at io.spring.javaformat.formatter.Formatter.lambda$format$1(Formatter.java:129)
	at io.spring.javaformat.formatter.Formatter.nlsSafe(Formatter.java:149)
	at io.spring.javaformat.formatter.Formatter.format(Formatter.java:129)
	at io.spring.javaformat.formatter.Formatter.format(Formatter.java:124)
```

Maybe you could have a look into this?

Best regards,
Fabian

**Comment by wilkinsona** [comment] 2020-06-29 21:29
Thanks for the report. This is a duplicate of https://github.com/spring-io/spring-javaformat/issues/195.

**Closed by wilkinsona** 2020-06-29 21:29 UTC
